- name: create db user
  become: true
  become_user: postgres
  postgresql_user:
    name={{POSTGRES_USER}}
    password={{POSTGRES_PASSWORD}}
    encrypted=yes
    state=present
    role_attr_flags=CREATEDB

- name: create mcod db
  become: true
  become_user: postgres
  postgresql_db:
    name={{POSTGRES_DB}}
    encoding='UTF-8'
    owner={{POSTGRES_USER}}
    state=present
  register: db_created
