#!/bin/bash

set -e


psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
    ALTER DATABASE $POSTGRES_DB OWNER TO $POSTGRES_USER;
    ALTER USER $POSTGRES_USER CREATEDB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL