# Generated by Django 2.0.4 on 2018-06-25 09:09

from django.db import migrations
import django.utils.timezone
import mcod.lib.model_utils


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_auto_20180525_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='modified',
            field=mcod.lib.model_utils.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                             verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=mcod.lib.model_utils.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                             verbose_name='modified'),
        ),
    ]
