- name: install redis server
  yum: name=ulyaoth-redis3 state=installed update_cache=yes
  become: yes

- name: enable and start redis server
  service: name=redis enabled=yes state=started
  become: yes